RainbowRobocodeDocumentation: mega.boirlerplate.OtherRobot Class Reference
mega.boirlerplate.OtherRobot Class Reference
Classes
enum PresentHistoryDatas
class Tick
Public Member Functions
OtherRobot (String name)
void advance ()
int compareTo (OtherRobot robot)
List< Tick > getAllHistory ()
Tick getHistory (int index)
int getHistorySize ()
void pushHistory (Tick tick)
List< WaveBullet > getAllBullets ()
WaveBullet getBullet (int index)
String getName ()
double getGunHeat (long time)
Vector predictLocation (int timeFrame, ProjectedBot.TurnBehaviours tb, ProjectedBot.SpeedBehaviours sb, State state)
PresentHistoryDatas availablePresentHistoryData (long time)
boolean predictBulletShot (long time, State state)
void onPaint (Graphics2D g, long time)
Private Attributes
String name
ArrayList< Tick > history = new ArrayList<Tick>(10000)
ArrayList< WaveBullet > bulletWaves = new ArrayList<WaveBullet>()
Detailed Description
Author
Gates
Definition at line 14 of file OtherRobot.java.
Constructor & Destructor Documentation
OtherRobot()
mega.boirlerplate.OtherRobot.OtherRobot (String name)
Parameters
name
Definition at line 71 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.name.
Member Function Documentation
advance()
void mega.boirlerplate.OtherRobot.advance ()
Definition at line 78 of file OtherRobot.java.
availablePresentHistoryData()
PresentHistoryDatas mega.boirlerplate.OtherRobot.availablePresentHistoryData (long time)
Parameters
time
Returns
Definition at line 205 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.getHistory(), mega.boirlerplate.OtherRobot.PresentHistoryDatas.none, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionOnly, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionVelocity, and mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionVelocityTurnRate.
Referenced by mega.boirlerplate.GunPredictive.execute().
compareTo()
int mega.boirlerplate.OtherRobot.compareTo (OtherRobot robot)
Definition at line 91 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.getHistory().
getAllBullets()
List<WaveBullet> mega.boirlerplate.OtherRobot.getAllBullets ()
Returns
Definition at line 135 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.bulletWaves.
getAllHistory()
List<Tick> mega.boirlerplate.OtherRobot.getAllHistory ()
Returns
Definition at line 99 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.history.
getBullet()
WaveBullet mega.boirlerplate.OtherRobot.getBullet (int index)
Parameters
index
Returns
Definition at line 144 of file OtherRobot.java.
References mega.boirlerplate.Util.modulo().
Referenced by mega.boirlerplate.OtherRobot.getGunHeat().
getGunHeat()
double mega.boirlerplate.OtherRobot.getGunHeat (long time)
Parameters
time
Returns
Definition at line 164 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.getBullet(), mega.boirlerplate.WaveBullet.getFlightTime(), and mega.boirlerplate.WaveBullet.getPower().
Referenced by mega.boirlerplate.OtherRobot.predictBulletShot().
getHistory()
Tick mega.boirlerplate.OtherRobot.getHistory (int index)
Parameters
index
Returns
Definition at line 108 of file OtherRobot.java.
References mega.boirlerplate.Util.modulo().
Referenced by mega.boirlerplate.OtherRobot.availablePresentHistoryData(), mega.boirlerplate.OtherRobot.compareTo(), mega.boirlerplate.RadarPriority.execute(), mega.boirlerplate.RadarTracking.execute(), mega.boirlerplate.GunSimple.execute(), mega.boirlerplate.GunPredictive.execute(), mega.boirlerplate.State.onScannedRobot(), mega.boirlerplate.OtherRobot.predictBulletShot(), and mega.boirlerplate.OtherRobot.predictLocation().
getHistorySize()
int mega.boirlerplate.OtherRobot.getHistorySize ()
Returns
Definition at line 119 of file OtherRobot.java.
getName()
String mega.boirlerplate.OtherRobot.getName ()
Returns
Definition at line 155 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.name.
Referenced by mega.boirlerplate.State.onRobotDeath().
onPaint()
void mega.boirlerplate.OtherRobot.onPaint (Graphics2D g, long time)
Parameters
g
time
Definition at line 295 of file OtherRobot.java.
predictBulletShot()
boolean mega.boirlerplate.OtherRobot.predictBulletShot (long time, State state)
Parameters
time
state
Returns
Definition at line 223 of file OtherRobot.java.
References mega.boirlerplate.Util.getAngle(), mega.boirlerplate.OtherRobot.getGunHeat(), mega.boirlerplate.OtherRobot.getHistory(), mega.boirlerplate.Util.isOutOfBattleField(), mega.boirlerplate.Util.ROBOT_HEIGHT, mega.boirlerplate.Util.ROBOT_WIDTH, and mega.boirlerplate.Util.roundTo1().
Referenced by mega.boirlerplate.State.onScannedRobot().
predictLocation()
Vector mega.boirlerplate.OtherRobot.predictLocation (int timeFrame, ProjectedBot.TurnBehaviours tb, ProjectedBot.SpeedBehaviours sb, State state)
Parameters
timeFrame
tb
sb
state
Returns
Definition at line 180 of file OtherRobot.java.
References mega.boirlerplate.OtherRobot.getHistory(), mega.boirlerplate.ProjectedBot.getPosition(), and mega.boirlerplate.ProjectedBot.project().
Referenced by mega.boirlerplate.GunPredictive.execute().
pushHistory()
void mega.boirlerplate.OtherRobot.pushHistory (Tick tick)
Parameters
tick
Definition at line 127 of file OtherRobot.java.
Referenced by mega.boirlerplate.State.onScannedRobot().
Member Data Documentation
bulletWaves
ArrayList<WaveBullet> mega.boirlerplate.OtherRobot.bulletWaves = new ArrayList<WaveBullet>() private
Definition at line 65 of file OtherRobot.java.
Referenced by mega.boirlerplate.OtherRobot.getAllBullets().
history
ArrayList<Tick> mega.boirlerplate.OtherRobot.history = new ArrayList<Tick>(10000) private
Definition at line 64 of file OtherRobot.java.
Referenced by mega.boirlerplate.OtherRobot.getAllHistory().
name
String mega.boirlerplate.OtherRobot.name private
Definition at line 63 of file OtherRobot.java.
Referenced by mega.boirlerplate.OtherRobot.getName(), and mega.boirlerplate.OtherRobot.OtherRobot().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/OtherRobot.java