RainbowRobocodeDocumentation: mega.boirlerplate.GunSimple Class Reference
mega.boirlerplate.GunSimple Class Reference
Public Member Functions
GunSimple (State state, double coefficient)
void execute ()
Public Member Functions inherited from mega.boirlerplate.Gun
Gun (State state)
double getBulletPower ()
double getRotation ()
boolean getShouldFire ()
void firedBullet (BulletTracked tb)
void bulletHit (BulletTracked tb)
void bulletMissed (BulletTracked tb)
Public Member Functions inherited from mega.boirlerplate.Component
Component (State state)
abstract void execute ()
void onHitRobot (HitRobotEvent e)
void onPaint (Graphics2D g)
Private Member Functions
double calculateRotation (double bearing)
Private Attributes
double coefficient
Additional Inherited Members
Protected Attributes inherited from mega.boirlerplate.Gun
double bulletPower
double rotation
boolean shouldFire = true
Protected Attributes inherited from mega.boirlerplate.Component
State state
Detailed Description
GunSimple extends Gun Create a simple rotational calc to shot enemy
Author
MatheusRV
Definition at line 17 of file GunSimple.java.
Constructor & Destructor Documentation
GunSimple()
mega.boirlerplate.GunSimple.GunSimple (State state, double coefficient)
A constructor Initialize Object
Parameters
state
coefficient a integer argument.
Definition at line 27 of file GunSimple.java.
References mega.boirlerplate.GunSimple.coefficient.
Member Function Documentation
calculateRotation()
double mega.boirlerplate.GunSimple.calculateRotation (double bearing) private
Parameters
bearing
Returns
< absolute rotation to enemy
< relative rotation to gun
< normalise
Definition at line 36 of file GunSimple.java.
References mega.boirlerplate.Gun.rotation, and mega.boirlerplate.Component.state.
Referenced by mega.boirlerplate.GunSimple.execute().
execute()
void mega.boirlerplate.GunSimple.execute ()
Definition at line 46 of file GunSimple.java.
References mega.boirlerplate.GunSimple.calculateRotation(), mega.boirlerplate.OtherRobot.getHistory(), mega.boirlerplate.Gun.rotation, and mega.boirlerplate.Component.state.
Member Data Documentation
coefficient
double mega.boirlerplate.GunSimple.coefficient private
Definition at line 19 of file GunSimple.java.
Referenced by mega.boirlerplate.GunSimple.GunSimple().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/GunSimple.java