RainbowRobocodeDocumentation: mega.boirlerplate.ProjectedBot Class Reference
mega.boirlerplate.ProjectedBot Class Reference
Classes
enum SpeedBehaviours
enum TurnBehaviours
Public Member Functions
ProjectedBot (OtherRobot.Tick tick)
ProjectedBot (double locXN, double locYN, double dirN, double speedN, double turnRateN)
ProjectedBot clone ()
void project (int timeFrame, TurnBehaviours tb, SpeedBehaviours sb, State state)
Vector getPosition ()
Private Attributes
double locX
double locY
double dir
double speed
double turnRate
Detailed Description
Author
Gates
Definition at line 8 of file ProjectedBot.java.
Constructor & Destructor Documentation
ProjectedBot() [1/2]
mega.boirlerplate.ProjectedBot.ProjectedBot (OtherRobot.Tick tick)
init a ProjectedBot from a tick
Parameters
tick
Definition at line 51 of file ProjectedBot.java.
Referenced by mega.boirlerplate.ProjectedBot.clone().
ProjectedBot() [2/2]
mega.boirlerplate.ProjectedBot.ProjectedBot (double locXN, double locYN, double dirN, double speedN, double turnRateN)
init a ProjectedBot from values
Parameters
locXN
locYN
dirN
speedN
turnRateN
Definition at line 72 of file ProjectedBot.java.
Member Function Documentation
clone()
ProjectedBot mega.boirlerplate.ProjectedBot.clone ()
Definition at line 85 of file ProjectedBot.java.
References mega.boirlerplate.ProjectedBot.ProjectedBot().
getPosition()
Vector mega.boirlerplate.ProjectedBot.getPosition ()
Returns
Definition at line 200 of file ProjectedBot.java.
Referenced by mega.boirlerplate.OtherRobot.predictLocation().
project()
void mega.boirlerplate.ProjectedBot.project (int timeFrame, TurnBehaviours tb, SpeedBehaviours sb, State state)
Parameters
timeFrame
tb
sb
state
Definition at line 97 of file ProjectedBot.java.
References mega.boirlerplate.Util.clamp(), and mega.boirlerplate.Util.speedToMaxTurnRate().
Referenced by mega.boirlerplate.OtherRobot.predictLocation().
Member Data Documentation
dir
double mega.boirlerplate.ProjectedBot.dir private
Definition at line 40 of file ProjectedBot.java.
locX
double mega.boirlerplate.ProjectedBot.locX private
Definition at line 37 of file ProjectedBot.java.
locY
double mega.boirlerplate.ProjectedBot.locY private
Definition at line 38 of file ProjectedBot.java.
speed
double mega.boirlerplate.ProjectedBot.speed private
Definition at line 41 of file ProjectedBot.java.
turnRate
double mega.boirlerplate.ProjectedBot.turnRate private
Definition at line 42 of file ProjectedBot.java.
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/ProjectedBot.java