RainbowRobocodeDocumentation: mega.boirlerplate.WaveEnemy Class Reference
mega.boirlerplate.WaveEnemy Class Reference
Public Member Functions
WaveEnemy (Vector position, double power, int startAngle, int endAngle, double confidence, State state)
boolean advance ()
long getFlightTime ()
double getPower ()
Vector getAveragePosition ()
void onPaint (Graphics2D g)
Private Attributes
ArrayList< BulletVirtual > bullets
double power
double confidence
Detailed Description
Definition at line 13 of file WaveEnemy.java.
Constructor & Destructor Documentation
WaveEnemy()
mega.boirlerplate.WaveEnemy.WaveEnemy (Vector position, double power, int startAngle, int endAngle, double confidence, State state)
Parameters
position
power
startAngle
endAngle
confidence
state
Definition at line 28 of file WaveEnemy.java.
References mega.boirlerplate.WaveEnemy.advance(), mega.boirlerplate.WaveEnemy.confidence, and mega.boirlerplate.WaveEnemy.power.
Member Function Documentation
advance()
boolean mega.boirlerplate.WaveEnemy.advance ()
Returns
Definition at line 42 of file WaveEnemy.java.
Referenced by mega.boirlerplate.WaveEnemy.WaveEnemy().
getAveragePosition()
Vector mega.boirlerplate.WaveEnemy.getAveragePosition ()
Returns
Definition at line 75 of file WaveEnemy.java.
References mega.boirlerplate.Vector.add(), and mega.boirlerplate.Vector.div().
Referenced by mega.boirlerplate.WaveEnemy.onPaint().
getFlightTime()
long mega.boirlerplate.WaveEnemy.getFlightTime ()
Returns
Definition at line 59 of file WaveEnemy.java.
getPower()
double mega.boirlerplate.WaveEnemy.getPower ()
Returns
Definition at line 67 of file WaveEnemy.java.
References mega.boirlerplate.WaveEnemy.power.
onPaint()
void mega.boirlerplate.WaveEnemy.onPaint (Graphics2D g)
Parameters
g
Definition at line 88 of file WaveEnemy.java.
References mega.boirlerplate.WaveEnemy.getAveragePosition().
Member Data Documentation
bullets
ArrayList<BulletVirtual> mega.boirlerplate.WaveEnemy.bullets private
Definition at line 15 of file WaveEnemy.java.
confidence
double mega.boirlerplate.WaveEnemy.confidence private
Definition at line 17 of file WaveEnemy.java.
Referenced by mega.boirlerplate.WaveEnemy.WaveEnemy().
power
double mega.boirlerplate.WaveEnemy.power private
Definition at line 16 of file WaveEnemy.java.
Referenced by mega.boirlerplate.WaveEnemy.getPower(), and mega.boirlerplate.WaveEnemy.WaveEnemy().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/WaveEnemy.java