RainbowRobocodeDocumentation: mega.boirlerplate.MovementPredictive Class Reference
mega.boirlerplate.MovementPredictive Class Reference
Classes
class Action
class Destination
Public Member Functions
MovementPredictive (State state)
void execute ()
void onHitRobot (HitRobotEvent e)
void onPaint (Graphics2D g)
Public Member Functions inherited from mega.boirlerplate.Movement
Movement (State state)
double getSpeed ()
double getRotation ()
boolean isOutOfBattleField (double x, double y, double margin)
Public Member Functions inherited from mega.boirlerplate.Component
Component (State state)
abstract void execute ()
void onHitRobot (HitRobotEvent e)
void onPaint (Graphics2D g)
Private Member Functions
double evaluatePosition (Vector position, double angle)
Destination pickBestPosition ()
void generateActions (Vector diff)
Private Attributes
Stack< Action > actions
ArrayList< Destination > destinations
Destination destination
Destination lastDestination
double lastEnemyBearing
Additional Inherited Members
Protected Attributes inherited from mega.boirlerplate.Movement
double speed
double rotation
Protected Attributes inherited from mega.boirlerplate.Component
State state
Detailed Description
Author
Gates
Definition at line 15 of file MovementPredictive.java.
Constructor & Destructor Documentation
MovementPredictive()
mega.boirlerplate.MovementPredictive.MovementPredictive (State state)
Parameters
state
Definition at line 68 of file MovementPredictive.java.
Member Function Documentation
evaluatePosition()
double mega.boirlerplate.MovementPredictive.evaluatePosition (Vector position, double angle) private
Parameters
position
angle
Returns
Definition at line 80 of file MovementPredictive.java.
References mega.boirlerplate.Vector.add(), mega.boirlerplate.MovementPredictive.Action.angle, mega.boirlerplate.Vector.equals(), mega.boirlerplate.Vector.getAngle(), mega.boirlerplate.Util.headinglessAngle(), mega.boirlerplate.Movement.isOutOfBattleField(), mega.boirlerplate.Vector.length(), mega.boirlerplate.Vector.lengthSq(), mega.boirlerplate.MovementPredictive.Destination.position, mega.boirlerplate.Vector.round(), and mega.boirlerplate.Component.state.
Referenced by mega.boirlerplate.MovementPredictive.pickBestPosition().
execute()
void mega.boirlerplate.MovementPredictive.execute ()
Definition at line 235 of file MovementPredictive.java.
References mega.boirlerplate.Vector.add(), mega.boirlerplate.MovementPredictive.Action.angle, mega.boirlerplate.MovementPredictive.destination, mega.boirlerplate.MovementPredictive.generateActions(), mega.boirlerplate.MovementPredictive.pickBestPosition(), mega.boirlerplate.MovementPredictive.Destination.position, mega.boirlerplate.Movement.rotation, mega.boirlerplate.MovementPredictive.Action.speed, and mega.boirlerplate.Component.state.
generateActions()
void mega.boirlerplate.MovementPredictive.generateActions (Vector diff) private
Parameters
diff
Definition at line 261 of file MovementPredictive.java.
References mega.boirlerplate.MovementPredictive.Action.Action(), mega.boirlerplate.Vector.getAngle(), mega.boirlerplate.Util.headinglessAngle(), mega.boirlerplate.Vector.length(), and mega.boirlerplate.Component.state.
Referenced by mega.boirlerplate.MovementPredictive.execute().
onHitRobot()
void mega.boirlerplate.MovementPredictive.onHitRobot (HitRobotEvent e)
Definition at line 281 of file MovementPredictive.java.
onPaint()
void mega.boirlerplate.MovementPredictive.onPaint (Graphics2D g)
Definition at line 289 of file MovementPredictive.java.
References mega.boirlerplate.Util.clamp(), and mega.boirlerplate.MovementPredictive.Destination.position.
pickBestPosition()
Destination mega.boirlerplate.MovementPredictive.pickBestPosition () private
Returns
Definition at line 193 of file MovementPredictive.java.
References mega.boirlerplate.Vector.add(), mega.boirlerplate.MovementPredictive.Action.angle, mega.boirlerplate.Vector.bound(), mega.boirlerplate.MovementPredictive.evaluatePosition(), mega.boirlerplate.Vector.getAngle(), mega.boirlerplate.Vector.rotate(), mega.boirlerplate.Component.state, and mega.boirlerplate.Vector.ZERO.
Referenced by mega.boirlerplate.MovementPredictive.execute().
Member Data Documentation
actions
Stack<Action> mega.boirlerplate.MovementPredictive.actions private
Definition at line 57 of file MovementPredictive.java.
destination
Destination mega.boirlerplate.MovementPredictive.destination private
Definition at line 59 of file MovementPredictive.java.
Referenced by mega.boirlerplate.MovementPredictive.execute().
destinations
ArrayList<Destination> mega.boirlerplate.MovementPredictive.destinations private
Definition at line 58 of file MovementPredictive.java.
lastDestination
Destination mega.boirlerplate.MovementPredictive.lastDestination private
Definition at line 60 of file MovementPredictive.java.
lastEnemyBearing
double mega.boirlerplate.MovementPredictive.lastEnemyBearing private
Definition at line 62 of file MovementPredictive.java.
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/MovementPredictive.java