RainbowRobocodeDocumentation: mega.boirlerplate.Vector Class Reference
mega.boirlerplate.Vector Class Reference
Public Member Functions
Vector (double x, double y)
Vector (Vector copy)
double length ()
double lengthSq ()
Vector add (Vector v, double coefficient)
Vector mul (double coefficient)
Vector div (double coefficient)
Vector rotate (double angle, Vector origin)
Vector add (Vector v)
Vector square ()
double getAngle ()
String toString ()
boolean equals (Vector v)
Vector round (int n)
Vector bound (double xMin, double xMax, double yMin, double yMax)
Static Public Attributes
static final Vector ZERO = new Vector(0, 0)
Detailed Description
Author
Gates
Definition at line 10 of file Vector.java.
Constructor & Destructor Documentation
Vector() [1/2]
mega.boirlerplate.Vector.Vector (double x, double y)
Parameters
x
y
Definition at line 19 of file Vector.java.
Referenced by mega.boirlerplate.Vector< HitRobotEvent >.add(), mega.boirlerplate.Vector< HitRobotEvent >.bound(), mega.boirlerplate.Vector< HitRobotEvent >.div(), mega.boirlerplate.Vector< HitRobotEvent >.mul(), mega.boirlerplate.Vector< HitRobotEvent >.rotate(), mega.boirlerplate.Vector< HitRobotEvent >.round(), and mega.boirlerplate.Vector< HitRobotEvent >.square().
Vector() [2/2]
mega.boirlerplate.Vector.Vector (Vector copy)
Parameters
copy
Definition at line 27 of file Vector.java.
Member Function Documentation
add() [1/2]
Vector mega.boirlerplate.Vector.add (Vector v, double coefficient)
Parameters
v
coefficient
Returns
Definition at line 53 of file Vector.java.
Referenced by mega.boirlerplate.Vector< HitRobotEvent >.add(), mega.boirlerplate.BulletVirtual.advance(), mega.boirlerplate.MovementPredictive.evaluatePosition(), mega.boirlerplate.GunPredictive.execute(), mega.boirlerplate.MovementPredictive.execute(), mega.boirlerplate.WaveEnemy.getAveragePosition(), mega.boirlerplate.WaveBullet.getAveragePosition(), mega.boirlerplate.RainbowSurf.onBulletHit(), mega.boirlerplate.RainbowSurf.onHitRobot(), and mega.boirlerplate.MovementPredictive.pickBestPosition().
add() [2/2]
Vector mega.boirlerplate.Vector.add (Vector v)
Parameters
v
Returns
Definition at line 103 of file Vector.java.
bound()
Vector mega.boirlerplate.Vector.bound (double xMin, double xMax, double yMin, double yMax)
Parameters
xMin
xMax
yMin
yMax
Returns
Definition at line 157 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.pickBestPosition().
div()
Vector mega.boirlerplate.Vector.div (double coefficient)
Parameters
coefficient
Returns
Definition at line 73 of file Vector.java.
Referenced by mega.boirlerplate.WaveEnemy.getAveragePosition(), mega.boirlerplate.WaveBullet.getAveragePosition(), and mega.boirlerplate.State.onScannedRobot().
equals()
boolean mega.boirlerplate.Vector.equals (Vector v)
Parameters
v
Returns
Definition at line 136 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.evaluatePosition().
getAngle()
double mega.boirlerplate.Vector.getAngle ()
Returns
Definition at line 119 of file Vector.java.
Referenced by mega.boirlerplate.State.calculateTurnRate(), mega.boirlerplate.MovementPredictive.evaluatePosition(), mega.boirlerplate.MovementPredictive.generateActions(), and mega.boirlerplate.MovementPredictive.pickBestPosition().
length()
double mega.boirlerplate.Vector.length ()
Returns
Definition at line 35 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.evaluatePosition(), mega.boirlerplate.MovementPredictive.generateActions(), and mega.boirlerplate.BulletVirtual.getPower().
lengthSq()
double mega.boirlerplate.Vector.lengthSq ()
Returns
Definition at line 43 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.evaluatePosition(), and mega.boirlerplate.Vector< HitRobotEvent >.length().
mul()
Vector mega.boirlerplate.Vector.mul (double coefficient)
Parameters
coefficient
Returns
Definition at line 63 of file Vector.java.
rotate()
Vector mega.boirlerplate.Vector.rotate (double angle, Vector origin)
Parameters
angle
origin
Returns
Definition at line 85 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.pickBestPosition().
round()
Vector mega.boirlerplate.Vector.round (int n)
Parameters
n
Returns
Definition at line 145 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.evaluatePosition().
square()
Vector mega.boirlerplate.Vector.square ()
Returns
Definition at line 111 of file Vector.java.
toString()
String mega.boirlerplate.Vector.toString ()
Returns
Definition at line 127 of file Vector.java.
Member Data Documentation
ZERO
final Vector mega.boirlerplate.Vector.ZERO = new Vector(0, 0) static
Definition at line 12 of file Vector.java.
Referenced by mega.boirlerplate.MovementPredictive.pickBestPosition().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/Vector.java