RainbowRobocodeDocumentation: mega.boirlerplate.BulletTracked Class Reference
mega.boirlerplate.BulletTracked Class Reference
Public Member Functions
BulletTracked (Bullet bullet)
Bullet getBullet ()
void setData (PredictionData dataN)
PredictionData getData ()
Private Attributes
Bullet bullet
PredictionData data
Detailed Description
Author
Gates
Definition at line 9 of file BulletTracked.java.
Constructor & Destructor Documentation
BulletTracked()
mega.boirlerplate.BulletTracked.BulletTracked (Bullet bullet)
Parameters
bullet
Definition at line 18 of file BulletTracked.java.
References mega.boirlerplate.BulletTracked.bullet.
Member Function Documentation
getBullet()
Bullet mega.boirlerplate.BulletTracked.getBullet ()
Returns
Definition at line 26 of file BulletTracked.java.
References mega.boirlerplate.BulletTracked.bullet.
Referenced by mega.boirlerplate.RainbowSurf.onBulletHit(), mega.boirlerplate.RainbowSurf.onBulletHitBullet(), and mega.boirlerplate.RainbowSurf.onBulletMissed().
getData()
PredictionData mega.boirlerplate.BulletTracked.getData ()
Returns
Definition at line 42 of file BulletTracked.java.
References mega.boirlerplate.BulletTracked.data.
setData()
void mega.boirlerplate.BulletTracked.setData (PredictionData dataN)
Parameters
dataN
Definition at line 34 of file BulletTracked.java.
Referenced by mega.boirlerplate.GunPredictive.firedBullet().
Member Data Documentation
bullet
Bullet mega.boirlerplate.BulletTracked.bullet private
Definition at line 11 of file BulletTracked.java.
Referenced by mega.boirlerplate.BulletTracked.BulletTracked(), and mega.boirlerplate.BulletTracked.getBullet().
data
PredictionData mega.boirlerplate.BulletTracked.data private
Definition at line 12 of file BulletTracked.java.
Referenced by mega.boirlerplate.BulletTracked.getData().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/BulletTracked.java