RainbowRobocodeDocumentation: mega.boirlerplate.WaveBullet Class Reference
mega.boirlerplate.WaveBullet Class Reference
Public Member Functions
WaveBullet (Vector position, double power, int startAngle, int endAngle, double confidence, State state)
boolean advance ()
long getFlightTime ()
double getPower ()
Vector getAveragePosition ()
void onPaint (Graphics2D g)
Private Attributes
ArrayList< BulletVirtual > bullets
double power
double confidence
Detailed Description
Author
Gates
Definition at line 15 of file WaveBullet.java.
Constructor & Destructor Documentation
WaveBullet()
mega.boirlerplate.WaveBullet.WaveBullet (Vector position, double power, int startAngle, int endAngle, double confidence, State state)
Parameters
position
power
startAngle
endAngle
confidence
state
Definition at line 30 of file WaveBullet.java.
References mega.boirlerplate.WaveBullet.advance(), mega.boirlerplate.WaveBullet.confidence, and mega.boirlerplate.WaveBullet.power.
Member Function Documentation
advance()
boolean mega.boirlerplate.WaveBullet.advance ()
Returns
Definition at line 44 of file WaveBullet.java.
Referenced by mega.boirlerplate.WaveBullet.WaveBullet().
getAveragePosition()
Vector mega.boirlerplate.WaveBullet.getAveragePosition ()
Returns
Definition at line 77 of file WaveBullet.java.
References mega.boirlerplate.Vector.add(), and mega.boirlerplate.Vector.div().
Referenced by mega.boirlerplate.WaveBullet.onPaint().
getFlightTime()
long mega.boirlerplate.WaveBullet.getFlightTime ()
Returns
Definition at line 61 of file WaveBullet.java.
Referenced by mega.boirlerplate.OtherRobot.getGunHeat().
getPower()
double mega.boirlerplate.WaveBullet.getPower ()
Returns
Definition at line 69 of file WaveBullet.java.
References mega.boirlerplate.WaveBullet.power.
Referenced by mega.boirlerplate.OtherRobot.getGunHeat().
onPaint()
void mega.boirlerplate.WaveBullet.onPaint (Graphics2D g)
Parameters
g
Definition at line 90 of file WaveBullet.java.
References mega.boirlerplate.WaveBullet.getAveragePosition().
Member Data Documentation
bullets
ArrayList<BulletVirtual> mega.boirlerplate.WaveBullet.bullets private
Definition at line 17 of file WaveBullet.java.
confidence
double mega.boirlerplate.WaveBullet.confidence private
Definition at line 19 of file WaveBullet.java.
Referenced by mega.boirlerplate.WaveBullet.WaveBullet().
power
double mega.boirlerplate.WaveBullet.power private
Definition at line 18 of file WaveBullet.java.
Referenced by mega.boirlerplate.WaveBullet.getPower(), and mega.boirlerplate.WaveBullet.WaveBullet().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/WaveBullet.java