RainbowRobocodeDocumentation: mega.boirlerplate.State Class Reference
mega.boirlerplate.State Class Reference
Public Member Functions
State (AdvancedRobot robot)
void advance ()
void onScannedRobot (ScannedRobotEvent e)
void onRobotDeath (RobotDeathEvent e)
Private Member Functions
Vector calculatePosition (double bearing, double distance)
Static Private Member Functions
static Vector calculateVelocity (Vector oldPosition, Vector newPosition)
static double calculateTurnRate (Vector oldVelocity, Vector newVelocity)
Detailed Description
State - the particular condition that someone or something is in at a specific time.
See: https://en.wikipedia.org/wiki/State_space
Author
VisualMelon
thomasleese
Cyanogenoid
Definition at line 19 of file State.java.
Constructor & Destructor Documentation
State()
mega.boirlerplate.State.State (AdvancedRobot robot)
Parameters
robot
Definition at line 38 of file State.java.
Member Function Documentation
advance()
void mega.boirlerplate.State.advance ()
Definition at line 48 of file State.java.
Referenced by mega.boirlerplate.RainbowSurf.run().
calculatePosition()
Vector mega.boirlerplate.State.calculatePosition (double bearing, double distance) private
Parameters
bearing
distance
Returns
Definition at line 120 of file State.java.
Referenced by mega.boirlerplate.State.onScannedRobot().
calculateTurnRate()
static double mega.boirlerplate.State.calculateTurnRate (Vector oldVelocity, Vector newVelocity) static private
Parameters
oldVelocity
newVelocity
Returns
Definition at line 144 of file State.java.
References mega.boirlerplate.Vector.getAngle().
Referenced by mega.boirlerplate.State.onScannedRobot().
calculateVelocity()
static Vector mega.boirlerplate.State.calculateVelocity (Vector oldPosition, Vector newPosition) static private
Parameters
oldPosition
newPosition
Returns
Definition at line 133 of file State.java.
Referenced by mega.boirlerplate.State.onScannedRobot().
onRobotDeath()
void mega.boirlerplate.State.onRobotDeath (RobotDeathEvent e)
Parameters
e
Definition at line 94 of file State.java.
References mega.boirlerplate.OtherRobot.getName().
Referenced by mega.boirlerplate.RainbowSurf.onRobotDeath().
onScannedRobot()
void mega.boirlerplate.State.onScannedRobot (ScannedRobotEvent e)
Parameters
e
Definition at line 60 of file State.java.
References mega.boirlerplate.State.calculatePosition(), mega.boirlerplate.State.calculateTurnRate(), mega.boirlerplate.State.calculateVelocity(), mega.boirlerplate.Vector.div(), mega.boirlerplate.OtherRobot.getHistory(), mega.boirlerplate.OtherRobot.predictBulletShot(), and mega.boirlerplate.OtherRobot.pushHistory().
Referenced by mega.boirlerplate.RainbowSurf.onScannedRobot().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/State.java