RainbowRobocodeDocumentation: mega.boirlerplate.RainbowSurf Class Reference
mega.boirlerplate.RainbowSurf Class Reference
Classes
enum Strategy
class StrategyComponents
Public Member Functions
RainbowSurf ()
void updateStrategy (Strategy strategy)
void getStrategy ()
void run ()
void onBattleEnded (BattleEndedEvent e)
void onBulletHit (BulletHitEvent e)
void onBulletHitBullet (BulletHitBulletEvent e)
void onBulletMissed (BulletMissedEvent e)
void onDeath (DeathEvent e)
void onHitByBullet (HitByBulletEvent e)
void onHitRobot (HitRobotEvent e)
void onHitWall (HitWallEvent e)
void onPaint (Graphics2D g)
void onRobotDeath (RobotDeathEvent e)
void onRoundEnded (RoundEndedEvent e)
void onScannedRobot (ScannedRobotEvent e)
void onWin (WinEvent e)
void onSkippedTurn (SkippedTurnEvent e)
void paintRobot ()
Private Member Functions
void initStrategies (final State state)
Private Attributes
Map< Strategy, RainbowSurf.StrategyComponents > strategyMap
State state
Radar radar
Gun gun
Movement movement
Detailed Description
Author
Gates
Definition at line 16 of file RainbowSurf.java.
Constructor & Destructor Documentation
RainbowSurf()
mega.boirlerplate.RainbowSurf.RainbowSurf ()
Definition at line 61 of file RainbowSurf.java.
References mega.boirlerplate.RainbowSurf.initStrategies(), and mega.boirlerplate.RainbowSurf.updateStrategy().
Member Function Documentation
getStrategy()
void mega.boirlerplate.RainbowSurf.getStrategy ()
Definition at line 119 of file RainbowSurf.java.
References mega.boirlerplate.RainbowSurf.updateStrategy().
Referenced by mega.boirlerplate.RainbowSurf.run().
initStrategies()
void mega.boirlerplate.RainbowSurf.initStrategies (final State state) private
Parameters
state
Definition at line 71 of file RainbowSurf.java.
References mega.boirlerplate.RainbowSurf.strategyMap.
Referenced by mega.boirlerplate.RainbowSurf.RainbowSurf().
onBattleEnded()
void mega.boirlerplate.RainbowSurf.onBattleEnded (BattleEndedEvent e)
Definition at line 182 of file RainbowSurf.java.
onBulletHit()
void mega.boirlerplate.RainbowSurf.onBulletHit (BulletHitEvent e)
Definition at line 190 of file RainbowSurf.java.
References mega.boirlerplate.Vector.add(), mega.boirlerplate.Gun.bulletHit(), and mega.boirlerplate.BulletTracked.getBullet().
onBulletHitBullet()
void mega.boirlerplate.RainbowSurf.onBulletHitBullet (BulletHitBulletEvent e)
Definition at line 211 of file RainbowSurf.java.
References mega.boirlerplate.BulletTracked.getBullet().
onBulletMissed()
void mega.boirlerplate.RainbowSurf.onBulletMissed (BulletMissedEvent e)
Definition at line 230 of file RainbowSurf.java.
References mega.boirlerplate.Gun.bulletMissed(), and mega.boirlerplate.BulletTracked.getBullet().
onDeath()
void mega.boirlerplate.RainbowSurf.onDeath (DeathEvent e)
Definition at line 249 of file RainbowSurf.java.
onHitByBullet()
void mega.boirlerplate.RainbowSurf.onHitByBullet (HitByBulletEvent e)
Definition at line 257 of file RainbowSurf.java.
onHitRobot()
void mega.boirlerplate.RainbowSurf.onHitRobot (HitRobotEvent e)
Definition at line 265 of file RainbowSurf.java.
References mega.boirlerplate.Vector.add(), and mega.boirlerplate.Component.onHitRobot().
onHitWall()
void mega.boirlerplate.RainbowSurf.onHitWall (HitWallEvent e)
Definition at line 277 of file RainbowSurf.java.
onPaint()
void mega.boirlerplate.RainbowSurf.onPaint (Graphics2D g)
Definition at line 285 of file RainbowSurf.java.
References mega.boirlerplate.Component.onPaint().
onRobotDeath()
void mega.boirlerplate.RainbowSurf.onRobotDeath (RobotDeathEvent e)
Definition at line 301 of file RainbowSurf.java.
References mega.boirlerplate.State.onRobotDeath().
onRoundEnded()
void mega.boirlerplate.RainbowSurf.onRoundEnded (RoundEndedEvent e)
Definition at line 306 of file RainbowSurf.java.
onScannedRobot()
void mega.boirlerplate.RainbowSurf.onScannedRobot (ScannedRobotEvent e)
Definition at line 314 of file RainbowSurf.java.
References mega.boirlerplate.State.onScannedRobot().
onSkippedTurn()
void mega.boirlerplate.RainbowSurf.onSkippedTurn (SkippedTurnEvent e)
Definition at line 335 of file RainbowSurf.java.
onWin()
void mega.boirlerplate.RainbowSurf.onWin (WinEvent e)
Definition at line 322 of file RainbowSurf.java.
paintRobot()
void mega.boirlerplate.RainbowSurf.paintRobot ()
Definition at line 342 of file RainbowSurf.java.
Referenced by mega.boirlerplate.RainbowSurf.run().
run()
void mega.boirlerplate.RainbowSurf.run ()
Definition at line 132 of file RainbowSurf.java.
References mega.boirlerplate.State.advance(), mega.boirlerplate.Component.execute(), mega.boirlerplate.Gun.firedBullet(), mega.boirlerplate.Gun.getBulletPower(), mega.boirlerplate.Radar.getRotation(), mega.boirlerplate.Gun.getRotation(), mega.boirlerplate.Movement.getRotation(), mega.boirlerplate.Gun.getShouldFire(), mega.boirlerplate.Movement.getSpeed(), mega.boirlerplate.RainbowSurf.getStrategy(), and mega.boirlerplate.RainbowSurf.paintRobot().
updateStrategy()
void mega.boirlerplate.RainbowSurf.updateStrategy (Strategy strategy)
Parameters
strategy
Definition at line 105 of file RainbowSurf.java.
References mega.boirlerplate.RainbowSurf.strategyMap.
Referenced by mega.boirlerplate.RainbowSurf.getStrategy(), and mega.boirlerplate.RainbowSurf.RainbowSurf().
Member Data Documentation
gun
Gun mega.boirlerplate.RainbowSurf.gun private
Definition at line 55 of file RainbowSurf.java.
movement
Movement mega.boirlerplate.RainbowSurf.movement private
Definition at line 56 of file RainbowSurf.java.
radar
Radar mega.boirlerplate.RainbowSurf.radar private
Definition at line 54 of file RainbowSurf.java.
state
State mega.boirlerplate.RainbowSurf.state private
Definition at line 52 of file RainbowSurf.java.
strategyMap
Map<Strategy, RainbowSurf.StrategyComponents> mega.boirlerplate.RainbowSurf.strategyMap private
Definition at line 50 of file RainbowSurf.java.
Referenced by mega.boirlerplate.RainbowSurf.initStrategies(), and mega.boirlerplate.RainbowSurf.updateStrategy().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/RainbowSurf.java