RainbowRobocodeDocumentation: mega.boirlerplate.Gun Class Reference
mega.boirlerplate.Gun Class Reference abstract
Public Member Functions
Gun (State state)
double getBulletPower ()
double getRotation ()
boolean getShouldFire ()
void firedBullet (BulletTracked tb)
void bulletHit (BulletTracked tb)
void bulletMissed (BulletTracked tb)
Public Member Functions inherited from mega.boirlerplate.Component
Component (State state)
abstract void execute ()
void onHitRobot (HitRobotEvent e)
void onPaint (Graphics2D g)
Protected Attributes
double bulletPower
double rotation
boolean shouldFire = true
Protected Attributes inherited from mega.boirlerplate.Component
State state
Detailed Description
Author
Gates
Definition at line 8 of file Gun.java.
Constructor & Destructor Documentation
Gun()
mega.boirlerplate.Gun.Gun (State state)
Parameters
state
Definition at line 18 of file Gun.java.
Member Function Documentation
bulletHit()
void mega.boirlerplate.Gun.bulletHit (BulletTracked tb)
Parameters
tb
Definition at line 58 of file Gun.java.
Referenced by mega.boirlerplate.RainbowSurf.onBulletHit().
bulletMissed()
void mega.boirlerplate.Gun.bulletMissed (BulletTracked tb)
Parameters
tb
Definition at line 66 of file Gun.java.
Referenced by mega.boirlerplate.RainbowSurf.onBulletMissed().
firedBullet()
void mega.boirlerplate.Gun.firedBullet (BulletTracked tb)
Parameters
tb
Definition at line 50 of file Gun.java.
Referenced by mega.boirlerplate.RainbowSurf.run().
getBulletPower()
double mega.boirlerplate.Gun.getBulletPower ()
Returns
Definition at line 26 of file Gun.java.
References mega.boirlerplate.Gun.bulletPower.
Referenced by mega.boirlerplate.RainbowSurf.run().
getRotation()
double mega.boirlerplate.Gun.getRotation ()
Returns
Definition at line 34 of file Gun.java.
References mega.boirlerplate.Gun.rotation.
Referenced by mega.boirlerplate.RainbowSurf.run().
getShouldFire()
boolean mega.boirlerplate.Gun.getShouldFire ()
Returns
Definition at line 42 of file Gun.java.
References mega.boirlerplate.Gun.shouldFire.
Referenced by mega.boirlerplate.RainbowSurf.run().
Member Data Documentation
bulletPower
double mega.boirlerplate.Gun.bulletPower protected
Definition at line 10 of file Gun.java.
Referenced by mega.boirlerplate.GunPredictive.execute(), and mega.boirlerplate.Gun.getBulletPower().
rotation
double mega.boirlerplate.Gun.rotation protected
Definition at line 11 of file Gun.java.
Referenced by mega.boirlerplate.GunSimple.calculateRotation(), mega.boirlerplate.GunRandom.execute(), mega.boirlerplate.GunSimple.execute(), mega.boirlerplate.GunPredictive.execute(), and mega.boirlerplate.Gun.getRotation().
shouldFire
boolean mega.boirlerplate.Gun.shouldFire = true protected
Definition at line 12 of file Gun.java.
Referenced by mega.boirlerplate.GunPredictive.execute(), and mega.boirlerplate.Gun.getShouldFire().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/Gun.java