RainbowRobocodeDocumentation: mega.boirlerplate.BulletVirtual Class Reference
mega.boirlerplate.BulletVirtual Class Reference
Public Member Functions
BulletVirtual (Vector position, double power, double angleD, State state)
boolean advance ()
Vector getPosition ()
double getPower ()
long getFlightTime ()
void onPaint (Graphics2D g)
Private Attributes
Vector position
Vector velocity
long flightTime
State state
Detailed Description
Author
Cyanogenoid
thomasleese
rikkiprince
Definition at line 11 of file BulletVirtual.java.
Constructor & Destructor Documentation
BulletVirtual()
mega.boirlerplate.BulletVirtual.BulletVirtual (Vector position, double power, double angleD, State state)
Parameters
position
power
angleD
state
Definition at line 25 of file BulletVirtual.java.
References mega.boirlerplate.Util.firepowerToSpeed(), and mega.boirlerplate.BulletVirtual.state.
Member Function Documentation
advance()
boolean mega.boirlerplate.BulletVirtual.advance ()
Returns
Definition at line 38 of file BulletVirtual.java.
References mega.boirlerplate.Vector.add(), and mega.boirlerplate.Util.isOutOfBattleField().
getFlightTime()
long mega.boirlerplate.BulletVirtual.getFlightTime ()
Returns
Definition at line 67 of file BulletVirtual.java.
References mega.boirlerplate.BulletVirtual.flightTime.
getPosition()
Vector mega.boirlerplate.BulletVirtual.getPosition ()
Returns
Definition at line 51 of file BulletVirtual.java.
References mega.boirlerplate.BulletVirtual.position.
getPower()
double mega.boirlerplate.BulletVirtual.getPower ()
Returns
Definition at line 59 of file BulletVirtual.java.
References mega.boirlerplate.Vector.length().
onPaint()
void mega.boirlerplate.BulletVirtual.onPaint (Graphics2D g)
Parameters
g
Definition at line 75 of file BulletVirtual.java.
Member Data Documentation
flightTime
long mega.boirlerplate.BulletVirtual.flightTime private
Definition at line 15 of file BulletVirtual.java.
Referenced by mega.boirlerplate.BulletVirtual.getFlightTime().
position
Vector mega.boirlerplate.BulletVirtual.position private
Definition at line 13 of file BulletVirtual.java.
Referenced by mega.boirlerplate.BulletVirtual.getPosition().
state
State mega.boirlerplate.BulletVirtual.state private
Definition at line 16 of file BulletVirtual.java.
Referenced by mega.boirlerplate.BulletVirtual.BulletVirtual().
velocity
Vector mega.boirlerplate.BulletVirtual.velocity private
Definition at line 14 of file BulletVirtual.java.
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/BulletVirtual.java