RainbowRobocodeDocumentation: mega.boirlerplate.Util Class Reference
mega.boirlerplate.Util Class Reference
Static Public Member Functions
static int modulo (int c, int mod)
static double clamp (double val, double lower, double upper)
static double round (double d, int digits)
static double roundTo1 (double d)
static double firepowerToSpeed (double firepower)
static double speedToFirepower (double speed)
static double speedToMaxTurnRate (double speed)
static double getDistance (double dx, double dy)
static double getAngle (double dx, double dy)
static double getDistance (double ax, double ay, double bx, double by)
static double getAngle (double ax, double ay, double bx, double by)
static boolean isOutOfBattleField (double x, double y, double width, double height, double marginLeft, double marginTop, double marginRight, double marginBottom)
static boolean isOutOfBattleField (Vector position, double width, double height, double marginLeft, double marginTop, double marginRight, double marginBottom)
static boolean isOutOfBattleField (double x, double y, double width, double height)
static boolean isOutOfBattleField (Vector position, double width, double height)
static double headinglessAngle (double angle)
Static Public Attributes
static final Random RANDOM = new Random()
static final int ROBOT_WIDTH = 48
static final int ROBOT_HEIGHT = 48
Detailed Description
Contains the collections framework, event model, utility classes and miscellaneous
Author
VisualMelon
thomasleese
Cyanogenoid
Definition at line 13 of file Util.java.
Member Function Documentation
clamp()
static double mega.boirlerplate.Util.clamp (double val, double lower, double upper) static
Parameters
val
lower
upper
Returns
Definition at line 37 of file Util.java.
Referenced by mega.boirlerplate.Vector< HitRobotEvent >.bound(), mega.boirlerplate.MovementPredictive.onPaint(), and mega.boirlerplate.ProjectedBot.project().
firepowerToSpeed()
static double mega.boirlerplate.Util.firepowerToSpeed (double firepower) static
Parameters
firepower
Returns
Definition at line 70 of file Util.java.
Referenced by mega.boirlerplate.BulletVirtual.BulletVirtual(), and mega.boirlerplate.GunPredictive.execute().
getAngle() [1/2]
static double mega.boirlerplate.Util.getAngle (double dx, double dy) static
Parameters
dx
dy
Returns
Definition at line 110 of file Util.java.
Referenced by mega.boirlerplate.GunPredictive.execute(), mega.boirlerplate.Vector< HitRobotEvent >.getAngle(), mega.boirlerplate.Util.getAngle(), and mega.boirlerplate.OtherRobot.predictBulletShot().
getAngle() [2/2]
static double mega.boirlerplate.Util.getAngle (double ax, double ay, double bx, double by) static
a is origin
Parameters
ax
ay
bx
by
Returns
Definition at line 138 of file Util.java.
References mega.boirlerplate.Util.getAngle().
getDistance() [1/2]
static double mega.boirlerplate.Util.getDistance (double dx, double dy) static
Parameters
dx
dy
Returns
Definition at line 99 of file Util.java.
Referenced by mega.boirlerplate.GunPredictive.execute(), and mega.boirlerplate.Util.getDistance().
getDistance() [2/2]
static double mega.boirlerplate.Util.getDistance (double ax, double ay, double bx, double by) static
Parameters
ax
ay
bx
by
Returns
Definition at line 123 of file Util.java.
References mega.boirlerplate.Util.getDistance().
headinglessAngle()
static double mega.boirlerplate.Util.headinglessAngle (double angle) static
Parameters
angle
Returns
Definition at line 212 of file Util.java.
Referenced by mega.boirlerplate.MovementPredictive.evaluatePosition(), and mega.boirlerplate.MovementPredictive.generateActions().
isOutOfBattleField() [1/4]
static boolean mega.boirlerplate.Util.isOutOfBattleField (double x, double y, double width, double height, double marginLeft, double marginTop, double marginRight, double marginBottom) static
Parameters
x
y
width
height
marginLeft
marginTop
marginRight
marginBottom
Returns
Definition at line 157 of file Util.java.
Referenced by mega.boirlerplate.BulletVirtual.advance(), mega.boirlerplate.Movement.isOutOfBattleField(), mega.boirlerplate.Util.isOutOfBattleField(), and mega.boirlerplate.OtherRobot.predictBulletShot().
isOutOfBattleField() [2/4]
static boolean mega.boirlerplate.Util.isOutOfBattleField (Vector position, double width, double height, double marginLeft, double marginTop, double marginRight, double marginBottom) static
Parameters
position
width
height
marginLeft
marginTop
marginRight
marginBottom
Returns
Definition at line 177 of file Util.java.
References mega.boirlerplate.Util.isOutOfBattleField().
isOutOfBattleField() [3/4]
static boolean mega.boirlerplate.Util.isOutOfBattleField (double x, double y, double width, double height) static
Parameters
x
y
width
height
Returns
Definition at line 192 of file Util.java.
References mega.boirlerplate.Util.isOutOfBattleField().
isOutOfBattleField() [4/4]
static boolean mega.boirlerplate.Util.isOutOfBattleField (Vector position, double width, double height) static
Parameters
position
width
height
Returns
Definition at line 203 of file Util.java.
References mega.boirlerplate.Util.isOutOfBattleField().
modulo()
static int mega.boirlerplate.Util.modulo (int c, int mod) static
Parameters
c
mod
Returns
Definition at line 25 of file Util.java.
Referenced by mega.boirlerplate.OtherRobot.getBullet(), and mega.boirlerplate.OtherRobot.getHistory().
round()
static double mega.boirlerplate.Util.round (double d, int digits) static
Parameters
d
digits
Returns
Definition at line 51 of file Util.java.
Referenced by mega.boirlerplate.Vector< HitRobotEvent >.round().
roundTo1()
static double mega.boirlerplate.Util.roundTo1 (double d) static
Parameters
d
Returns
Definition at line 61 of file Util.java.
Referenced by mega.boirlerplate.OtherRobot.predictBulletShot().
speedToFirepower()
static double mega.boirlerplate.Util.speedToFirepower (double speed) static
Parameters
speed
Returns
Definition at line 79 of file Util.java.
Referenced by mega.boirlerplate.GunPredictive.execute().
speedToMaxTurnRate()
static double mega.boirlerplate.Util.speedToMaxTurnRate (double speed) static
Parameters
speed
Returns
Definition at line 89 of file Util.java.
Referenced by mega.boirlerplate.ProjectedBot.project().
Member Data Documentation
RANDOM
final Random mega.boirlerplate.Util.RANDOM = new Random() static
Definition at line 15 of file Util.java.
Referenced by mega.boirlerplate.RadarPriority.execute().
ROBOT_HEIGHT
final int mega.boirlerplate.Util.ROBOT_HEIGHT = 48 static
Definition at line 17 of file Util.java.
Referenced by mega.boirlerplate.OtherRobot.predictBulletShot().
ROBOT_WIDTH
final int mega.boirlerplate.Util.ROBOT_WIDTH = 48 static
Definition at line 16 of file Util.java.
Referenced by mega.boirlerplate.OtherRobot.predictBulletShot().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/Util.java