RainbowRobocodeDocumentation: mega.boirlerplate.GunPredictive Class Reference
mega.boirlerplate.GunPredictive Class Reference
Public Member Functions
GunPredictive (State state, double coefficient)
void execute ()
void firedBullet (BulletTracked tb)
void bulletHit (BulletTracked tb)
void bulletMissed (BulletTracked tb)
void onPaint (Graphics2D g)
void onHitRobot (HitRobotEvent e)
Public Member Functions inherited from mega.boirlerplate.Gun
Gun (State state)
double getBulletPower ()
double getRotation ()
boolean getShouldFire ()
void firedBullet (BulletTracked tb)
void bulletHit (BulletTracked tb)
void bulletMissed (BulletTracked tb)
Public Member Functions inherited from mega.boirlerplate.Component
Component (State state)
abstract void execute ()
void onHitRobot (HitRobotEvent e)
void onPaint (Graphics2D g)
Private Attributes
double coefficient
boolean shouldFireNextTick = false
double nextProjectileSpeed = 19.7
double expectedGunDir = 0
Vector predVec
ArrayList< Vector > paintPreds = new ArrayList<Vector>()
OtherRobot.PresentHistoryDatas phs = OtherRobot.PresentHistoryDatas.none
PredictionData pd = null
int missCount = 0
int predCycle = 0
int maxPredCycle = 1
Static Private Attributes
static final double MIN_SHOOT_SPEED = 18.7
Additional Inherited Members
Protected Attributes inherited from mega.boirlerplate.Gun
double bulletPower
double rotation
boolean shouldFire = true
Protected Attributes inherited from mega.boirlerplate.Component
State state
Detailed Description
Author
Gates
Definition at line 14 of file GunPredictive.java.
Constructor & Destructor Documentation
GunPredictive()
mega.boirlerplate.GunPredictive.GunPredictive (State state, double coefficient)
Parameters
state
coefficient
Definition at line 38 of file GunPredictive.java.
References mega.boirlerplate.GunPredictive.coefficient.
Member Function Documentation
bulletHit()
void mega.boirlerplate.GunPredictive.bulletHit (BulletTracked tb)
Definition at line 154 of file GunPredictive.java.
bulletMissed()
void mega.boirlerplate.GunPredictive.bulletMissed (BulletTracked tb)
Definition at line 159 of file GunPredictive.java.
execute()
void mega.boirlerplate.GunPredictive.execute ()
Definition at line 47 of file GunPredictive.java.
References mega.boirlerplate.Vector.add(), mega.boirlerplate.OtherRobot.availablePresentHistoryData(), mega.boirlerplate.Gun.bulletPower, mega.boirlerplate.Util.firepowerToSpeed(), mega.boirlerplate.Util.getAngle(), mega.boirlerplate.Util.getDistance(), mega.boirlerplate.OtherRobot.getHistory(), mega.boirlerplate.ProjectedBot.SpeedBehaviours.keepSpeed, mega.boirlerplate.ProjectedBot.TurnBehaviours.keepTurn, mega.boirlerplate.GunPredictive.MIN_SHOOT_SPEED, mega.boirlerplate.GunPredictive.phs, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionVelocity, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionVelocityTurnRate, mega.boirlerplate.OtherRobot.predictLocation(), mega.boirlerplate.ProjectedBot.SpeedBehaviours.reverse, mega.boirlerplate.Gun.rotation, mega.boirlerplate.Gun.shouldFire, mega.boirlerplate.GunPredictive.shouldFireNextTick, mega.boirlerplate.Util.speedToFirepower(), and mega.boirlerplate.Component.state.
firedBullet()
void mega.boirlerplate.GunPredictive.firedBullet (BulletTracked tb)
Definition at line 149 of file GunPredictive.java.
References mega.boirlerplate.BulletTracked.setData().
onHitRobot()
void mega.boirlerplate.GunPredictive.onHitRobot (HitRobotEvent e)
Definition at line 204 of file GunPredictive.java.
References mega.boirlerplate.Component.state.
onPaint()
void mega.boirlerplate.GunPredictive.onPaint (Graphics2D g)
Definition at line 175 of file GunPredictive.java.
References mega.boirlerplate.OtherRobot.PresentHistoryDatas.none, mega.boirlerplate.GunPredictive.phs, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionOnly, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionVelocity, mega.boirlerplate.OtherRobot.PresentHistoryDatas.positionVelocityTurnRate, and mega.boirlerplate.Component.state.
Member Data Documentation
coefficient
double mega.boirlerplate.GunPredictive.coefficient private
Definition at line 18 of file GunPredictive.java.
Referenced by mega.boirlerplate.GunPredictive.GunPredictive().
expectedGunDir
double mega.boirlerplate.GunPredictive.expectedGunDir = 0 private
Definition at line 21 of file GunPredictive.java.
maxPredCycle
int mega.boirlerplate.GunPredictive.maxPredCycle = 1 private
Definition at line 31 of file GunPredictive.java.
MIN_SHOOT_SPEED
final double mega.boirlerplate.GunPredictive.MIN_SHOOT_SPEED = 18.7 static private
Definition at line 16 of file GunPredictive.java.
Referenced by mega.boirlerplate.GunPredictive.execute().
missCount
int mega.boirlerplate.GunPredictive.missCount = 0 private
Definition at line 29 of file GunPredictive.java.
nextProjectileSpeed
double mega.boirlerplate.GunPredictive.nextProjectileSpeed = 19.7 private
Definition at line 20 of file GunPredictive.java.
paintPreds
ArrayList<Vector> mega.boirlerplate.GunPredictive.paintPreds = new ArrayList<Vector>() private
Definition at line 25 of file GunPredictive.java.
pd
PredictionData mega.boirlerplate.GunPredictive.pd = null private
Definition at line 27 of file GunPredictive.java.
phs
OtherRobot.PresentHistoryDatas mega.boirlerplate.GunPredictive.phs = OtherRobot.PresentHistoryDatas.none private
Definition at line 26 of file GunPredictive.java.
Referenced by mega.boirlerplate.GunPredictive.execute(), and mega.boirlerplate.GunPredictive.onPaint().
predCycle
int mega.boirlerplate.GunPredictive.predCycle = 0 private
Definition at line 30 of file GunPredictive.java.
predVec
Vector mega.boirlerplate.GunPredictive.predVec private
Definition at line 23 of file GunPredictive.java.
shouldFireNextTick
boolean mega.boirlerplate.GunPredictive.shouldFireNextTick = false private
Definition at line 19 of file GunPredictive.java.
Referenced by mega.boirlerplate.GunPredictive.execute().
The documentation for this class was generated from the following file:
D:/Cloud/OneDrive/Dev/eclipse-workspace/RainbowSurf/src/mega/boirlerplate/GunPredictive.java